//Donations
export const CREATE_DONATION = 'CREATE_DONATION';
export const FETCH_DONATIONS = 'FETCH_DONATIONS';
export const FETCH_DONATION = 'FETCH_DONATION';

//Events
export const CREATE_EVENT = 'CREATE_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENT = 'FETCH_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';

//Banquet Room Rent Request
export const CREATE_RENT_REQUEST = 'CREATE_RENT_REQUEST';
export const FETCH_RENT_REQUESTS = 'FETCH_RENT_REQUESTS';
export const FETCH_RENT_REQUEST = 'FETCH_RENT_REQUEST';
export const DELETE_RENT_REQUEST = 'DELETE_RENT_REQUEST';
export const EDIT_RENT_REQUEST = 'EDIT_RENT_REQUEST';

//News
export const CREATE_NEWS = 'CREATE_NEWS';
export const FETCH_ALL_NEWS = 'FETCH_ALL_NEWS';
export const FETCH_NEWS = 'FETCH_NEWS';
export const DELETE_NEWS = 'DELETE_NEWS';
export const EDIT_NEWS = 'EDIT_NEWS';

//Volunteer
export const CREATE_VOLUNTEER_REQUEST = 'CREATE_VOLUNTEER_REQUEST';
export const FETCH_VOLUNTEER_REQUESTS = 'FETCH_VOLUNTEER_REQUESTS';
export const FETCH_VOLUNTEER_REQUEST = 'FETCH_VOLUNTEER_REQUEST';
export const DELETE_VOLUNTEER_REQUEST = 'DELETE_VOLUNTEER_REQUEST';
export const EDIT_VOLUNTEER_REQUEST = 'EDIT_VOLUNTEER_REQUEST';

//Newsletter
export const CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION';
export const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS';
// export const FETCH_SUBSCRIPTION = 'FETCH_SUBSCRIPTION'; I don't think this one is necessary since you only subcribe with email (marco)
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';
// export const EDIT_SUBSCRIPTION = 'EDIT_SUBSCRIPTION'; Same with this one (marco)
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const GET_PAGES = 'GET_PAGES';
export const GET_HEROS = 'GET_HEROS';
